name: example
description: An example app to show the usage of the IntroViewsFlutter package.

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  intro_views_flutter:
    path: ../

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/